### ISSUE TITLE
can't push additional branch 

### ISSUE THREAD

**Issue by shayanekat** [redcraft-org/redcraft_website#28]
I created a new branch locally in my computer, and I can't push it using `git push origin shaykat-frontend-fixe`

I get this error  message: 
 `
remote: Permission to redcraft-org/redcraft_website.git denied to shayanekat.
fatal: unable to access 'https://github.com/redcraft-org/redcraft_website.git/': The requested URL returned error: 403 `

**Comment by Cod3lta** [comment]
I invited you to the repository, you should be able to write after accepting the pending invitation 🙂
